#include <stdint.h>
#include <pic32mx.h>
#include "header.h"


void system_init(void)
{
	// Intitial system startup

	//  This will set the peripheral bus clock to the same frequency
	//  as the sysclock. That means 80 MHz, when the microcontroller
	//  is running at 80 MHz.

	SYSKEY = 0xAA996655;  // Unlock OSCCON, step 1
	SYSKEY = 0x556699AA;  // Unlock OSCCON, step 2
	while(OSCCON & (1 << 21)); // Wait until PBDIV ready
	OSCCONCLR = 0x180000; // clear PBDIV bit <0,1>
	while(OSCCON & (1 << 21));  // Wait until PBDIV ready
	SYSKEY = 0x0;  // Lock OSCCON

  // Set up output pins
	AD1PCFG = 0xFFFF;
	ODCE = 0x0;
	TRISECLR = 0xFF;
	PORTE = 0x0;

	// Set up input pins
	TRISDSET = (1 << 8);
	TRISFSET = (1 << 1);
}

void oledhost_init(void)
{
	// Setup on Uno32 need for oled usage

	// Set up SPI as master
	IECCLR(1) = 0x70; // Disables SPI interrupts
	SPI2CON= 0; // Stop and reset the SPI module
	SPI1BUF = 0; // Clear the receive buffer.
	SPI2BRG = 4; //Write the Baud Rate register
	SPI2STATCLR = 0x40; //Clear the SPIROV bit
	SPI2CONSET = 0x40; // CKP = 1
	SPI2CONSET = 0x20; // Write the desired settings to the SPIxCON register with MSTEN
	SPI2CONSET = 0x8000; //Enable SPI operation by setting the ON bit

	// Output pins for display signals
	PORTF = 0xFFFF;
	PORTG = (1 << 9);
	ODCF = 0x0;
	ODCG = 0x0;
	TRISFCLR = 0x70;
	TRISGCLR = 0x200;

}

void btn_init(void)
{
	TRISDSET = 0x7e0; // Sets btn 4 to 2 as input
	TRISFSET = 2; // Sets btn1 as input
}

void interupt_init(void)
{
	// Setup for interrupts

	T2CON = 0x70; // sets prescaler to 256 and stops timer
	PR2 = 3125;  // PR2 = (80000000/256)/100 , sets period register
	TMR2 = 0; // set counter to 0;

	IEC(0) |= (1 << 8); // Interrupt enable control for timer 2
	IPC(2) = (1 << 2); // configures interupt pritorty  for timer 2
	IFS(0) &= ~0x100; // clears timer 2 interrupt flag

	asm volatile("ei"); // enables interrupts

	T2CONSET = 0x8000; // starts counter;
}

void i2c_init(void)
{
	// Setup for i2c communication, used to access eeprom
	uint16_t temp;

	I2C1CON = 0x0;
	// I2C Baud rate should be less than 400 kHz, is generated by dividing
	//the 40 MHz peripheral bus clock down
	I2C1BRG = 0x0C2;
	I2C1STAT = 0x0;
	I2C1CONSET = 1 << 13; //SIDL = 1
	I2C1CONSET = 1 << 15; // ON = 1
	temp = I2C1RCV; //Clear receive buffer
}

void init(void)
{
	// System startup
  system_init();
  oledhost_init();
	display_init();
	btn_init();
	i2c_init();
	interupt_init();
}
